name: PR comment
on: workflow_dispatch
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: PR comment
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "PR commented"}'
         
