name: Minify JS Files
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -  name: Minify-JS Action
       uses: jossydevers/minify-js@v1.0.0
       with:
         exclude: '../JS/1.js'
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Minify source code
        branch: ${{ github.ref }}
