name: Minify files
on:
 workflow_dispatch:
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          npm install -g uglifycss
          npm install -g uglify-js
      - name: Minify JS and CSS files
        run: |
          mkdir minified
          uglifyjs ../JS/1.js -m -c -o minified/
        working-directory: ${{ github.workspace }}
