name: Minify files
on:
 workflow_dispatch:
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
         node-version: '14.x'
      - run: npm install
      - name: Install dependencies
        run: |
          npm install terser
          npm install -g uglifycss
          npm install -g uglify-js
      - name: Minify JS and CSS files
        run: |
          uglifyjs ../JS/1.js -m -c -o minified/
        working-directory: ${{ github.workspace }}
